#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="$ROOT/publish/caretta"
VERSION="$(awk -F '"' '/^version = / { print $2; exit }' "$ROOT/Cargo.toml")"
EDITION="$(awk -F '"' '/^edition = / { print $2; exit }' "$ROOT/Cargo.toml")"
LICENSE="$(awk -F '"' '/^license = / { print $2; exit }' "$ROOT/Cargo.toml")"
DESCRIPTION="$(awk -F '"' '/^description = / { print $2; exit }' "$ROOT/Cargo.toml")"
REPOSITORY="$(awk -F '"' '/^repository = / { print $2; exit }' "$ROOT/Cargo.toml")"
HOMEPAGE="$(awk -F '"' '/^homepage = / { print $2; exit }' "$ROOT/Cargo.toml")"

if [[ -z "$VERSION" || -z "$EDITION" || -z "$LICENSE" ]]; then
  echo "failed to read workspace package metadata from $ROOT/Cargo.toml" >&2
  exit 1
fi

if [[ -d "$STAGE" ]]; then
  if [[ -f "$STAGE/.caretta-generated" ]] ||
     [[ -z "$(find "$STAGE" -mindepth 1 ! -path "$STAGE/target" ! -path "$STAGE/target/*" -type f -print -quit)" ]]; then
    rm -rf "$STAGE"
  else
    echo "$STAGE exists and was not generated by this script; refusing to overwrite it" >&2
    exit 1
  fi
fi

mkdir -p "$STAGE/src" "$STAGE/publish"
printf 'generated by scripts/stage-crates-io.sh\n' > "$STAGE/.caretta-generated"

cp "$ROOT/README.md" "$STAGE/README.md"
cp "$ROOT/LICENSE-APACHE" "$STAGE/LICENSE-APACHE"
cp "$ROOT/LICENSE-MIT" "$STAGE/LICENSE-MIT"
cp "$ROOT/Cargo.lock" "$STAGE/Cargo.lock"
if [[ -f "$ROOT/caretta.png" ]]; then
  cp "$ROOT/caretta.png" "$STAGE/caretta.png"
fi

cp -R "$ROOT/assets" "$STAGE/assets"
cp "$ROOT/crates/agent-runtime/package.json" "$STAGE/package.json"
cp "$ROOT/crates/agent-runtime/bun.lock" "$STAGE/bun.lock"

cp -R "$ROOT/crates/cli/src/." "$STAGE/src/"
cp "$ROOT/crates/agent-common/src/lib.rs" "$STAGE/src/agent_common.rs"
cp "$ROOT/crates/cli-common/src/lib.rs" "$STAGE/src/cli_common.rs"
perl -0pi -e '
  s/pub use cli_common::\*;/pub use crate::cli_common_impl::*;/g;
' "$STAGE/src/agent/types.rs"
perl -0pi -e '
  s/pub use cli_common::\{PendingIssue, PrAuthor, PrSummary, TrackerInfo\};/pub use crate::cli_common_impl::{PendingIssue, PrAuthor, PrSummary, TrackerInfo};/g;
' "$STAGE/src/agent/tracker.rs"
perl -0pi -e '
  s/pub use agent_common::AgentCliAdapter as ProviderCliWrapper;/pub use crate::agent_common_impl::AgentCliAdapter as ProviderCliWrapper;/g;
  s/pub use agent_common::\{AgentCliAdapter, AgentCliCommand, AgentInvocation\};/pub use crate::agent_common_impl::{AgentCliAdapter, AgentCliCommand, AgentInvocation};/g;
' "$STAGE/src/cli_common.rs"

for crate in claude cline codex copilot gemini grok junie xai; do
  mkdir -p "$STAGE/src/$crate"
  cp -R "$ROOT/crates/$crate/src/." "$STAGE/src/$crate/"
  rm -f "$STAGE/src/$crate/main.rs"
done

mkdir -p "$STAGE/src/agent_runtime"
cp -R "$ROOT/crates/agent-runtime/src/." "$STAGE/src/agent_runtime/"
perl -0pi -e '
  s/use crate::bundled_agents::/use super::bundled_agents::/g;
  s/use crate::utilities::/use super::utilities::/g;
' "$STAGE/src/agent_runtime/available_models.rs"

cat > "$STAGE/Cargo.toml" <<EOF
[package]
name = "caretta"
version = "$VERSION"
edition = "$EDITION"
description = "$DESCRIPTION"
license = "$LICENSE"
repository = "$REPOSITORY"
homepage = "$HOMEPAGE"
readme = "README.md"
exclude = ["dist/", "node_modules/", "target/", ".caretta-generated"]

[lib]
name = "caretta"
path = "src/lib.rs"

[[bin]]
name = "caretta"
path = "src/main.rs"

[features]
default = []
bundle-runtime = ["dep:flate2", "dep:tar"]

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
rust-embed = { version = "8.5", features = ["interpolate-folder-path"] }
jsonwebtoken = "9"
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }
handlebars = "6"
serde_yaml = "0.9"
indexmap = { version = "2", features = ["serde"] }
tempfile = "3"
walkdir = "2.5.0"
flate2 = { version = "1", optional = true }
tar = { version = "0.4", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
tokio = { version = "1", features = ["full"] }
toak-rs = { version = "6.0.3", default-features = false }
keyring = "3"
dirs = "6"
axum = "0.7"
mime_guess = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.6", features = ["web"] }
tokio = { version = "1", features = ["rt", "sync", "macros", "time"] }
gloo-net = "0.2"

[build-dependencies]
flate2 = "1"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10"
tar = "0.4"
walkdir = "2.5.0"

[workspace]
EOF

cat > "$STAGE/src/lib.rs" <<'EOF'
#![allow(dead_code, non_snake_case, unused_imports)]

extern crate self as agent_common;
extern crate self as agent_runtime;
extern crate self as claude;
extern crate self as cli_common;
extern crate self as cline;
extern crate self as codex;
extern crate self as copilot;
extern crate self as gemini;
extern crate self as grok;
extern crate self as junie;
extern crate self as xai;

#[path = "agent_common.rs"]
mod agent_common_impl;
use agent_common_impl::*;

#[path = "cli_common.rs"]
mod cli_common_impl;
use cli_common_impl::*;

#[path = "claude/lib.rs"]
mod claude_impl;
use claude_impl::*;

#[path = "cline/lib.rs"]
mod cline_impl;
use cline_impl::*;

#[path = "codex/lib.rs"]
mod codex_impl;
use codex_impl::*;

#[path = "copilot/lib.rs"]
mod copilot_impl;
use copilot_impl::*;

#[path = "gemini/lib.rs"]
mod gemini_impl;
use gemini_impl::*;

#[path = "grok/lib.rs"]
mod grok_impl;
use grok_impl::*;

#[path = "junie/lib.rs"]
mod junie_impl;
use junie_impl::*;

#[path = "xai/lib.rs"]
mod xai_impl;
use xai_impl::*;

#[path = "agent_runtime/lib.rs"]
mod agent_runtime_impl;
use agent_runtime_impl::*;

EOF

awk 'seen || /^pub mod agent;$/ { seen = 1; print }' "$ROOT/crates/cli/src/lib.rs" >> "$STAGE/src/lib.rs"

cp "$ROOT/crates/cli/build.rs" "$STAGE/build_cli.rs"
perl -0pe '
  s#src/bundled_agents\.rs#src/agent_runtime/bundled_agents.rs#g;
  s#src/utilities\.rs#src/agent_runtime/utilities.rs#g;
  s#src/available_models\.rs#src/agent_runtime/available_models.rs#g;
  s/let repo_root = manifest_dir\s*\n\s*\.parent\(\)\s*\n\s*\.and_then\(Path::parent\)\s*\n\s*\.expect\("caretta-agent-runtime should live at workspace\/crates\/agent-runtime"\);/let repo_root = manifest_dir.clone();/s;
  s/available_models::scan_available_models\(repo_root,/available_models::scan_available_models(\&repo_root,/g;
  s/if stamp_matches\(stamp_path, key\) && manifest_dir\.join\("node_modules"\)\.is_dir\(\) \{\s*return;\s*\}/if manifest_dir.join("node_modules").is_dir() {\n        return;\n    }/s;
' "$ROOT/crates/agent-runtime/build.rs" > "$STAGE/build_agent_runtime.rs"

cat > "$STAGE/build.rs" <<'EOF'
mod cli_build {
    include!("build_cli.rs");

    pub fn run() {
        main();
    }
}

mod agent_runtime_build {
    include!("build_agent_runtime.rs");

    pub fn run() {
        main();
    }
}

fn main() {
    cli_build::run();
    agent_runtime_build::run();
}
EOF

if [[ -d "$ROOT/crates/agent-runtime/node_modules" ]]; then
  ln -s "../../crates/agent-runtime/node_modules" "$STAGE/node_modules"
fi

echo "Staged crates.io package at $STAGE"
echo "Verify:  cargo package --manifest-path publish/caretta/Cargo.toml --allow-dirty --no-verify"
echo "Publish: cargo publish --manifest-path publish/caretta/Cargo.toml --no-verify"
